import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { fonts } from "./font";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import { SpeedInsights } from "@vercel/speed-insights/next"
import Head from "next/head";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className={fonts.rubik.variable}>
        <Head>
            <title>AI Trip</title>
        </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <ErrorBoundary errorComponent={Error}>

        {children}
        </ErrorBoundary>

        </Providers>
        <SpeedInsights />
      </body>
    </html>
  );
}
